dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: T9c2/66xLYWVLxjW80qgimUmGlMdIKa1as275dWJErpt22JJtYYyd58HqdjOV7uzqYEwIA0lkWykQUl5sNmOabelMEL2pvAvuPCVCvQAffdbZv+Z7NRGGoKKBnoYI/g++cU1X6dSMxOPxF0lskkxxeavSsD3kaappVuTrSRIGzJ3QEQdhDfgQ7ilgF/tRK12gaIccQvGm61yPc47GHE2kuTNn1GOFzbCuIJU096n4qmDkQp7UK2cSZTrixjc0HsEdamO8sXetusffYh0v1H27dwRN57fj0eqpBD95uLHiJS4ytHHwwsEENQtrYhBVAr7EB3o4iZx/qkZyICDPIE9DAjfL5FHKsRJECU/VQ98WtRq6R/UvJnoJCYQATfcNb4nN90yWR9s+4MypGdW7UebqxUIe/xsT1Xj5/rn8ebNsDX/ri5JWm+1Shg6UJsbjWXs8Z2V+V8a+aW7cCWqUDaZtbUVUKf6jWmPy7KFjsOUCVKiYc1CWEE6kZnXhaM3s2Oj2c3LB/CNbgkdwDjAN6h0ZJwjdl5lo1Az+XTWf2IU19nLt1AKYnDWUbc7maWvmdvh6gVuistVgyeFLM3PJpkou+99NMWtEF5ZYgs0uyUzC8LIme02Ta2vVmDtLB1t0+k56zJMjzECbUMhw8XPI4Ri3JYKYAgwUU+zd7U5qwUn7GU=
