global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#stanislav_ivanov'